In [1]:
# importing a numerical python library also called Numpy ,numpy is very-very usefull whether it is ML,DL,NLP,computer vision etc for dealing with matrixes,arrays etc

In [2]:
# importing numpy 
import numpy as np

In [3]:
#  say i want to create a array 
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
type(np.array([1,2,3,4])) 


numpy.ndarray

In [5]:
# as u can see it is a array as 'nd' means it is n-dimensional 

In [8]:
# if i add string inside list than in such case every item in array will be string too whether it is was interger,complex no. etc 
np.array([1,2,3,4,'sachin',2+2j])

array(['1', '2', '3', '4', 'sachin', '(2+2j)'], dtype='<U64')

In [9]:
# say if i add any floating no. inside a list with integer no. than the array as reslt will have all items as float like
np.array([1,2,3,4,5.0])

array([1., 2., 3., 4., 5.])

In [11]:
#  if i add lists inside list than in this case resulted array will be 
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [12]:
np.array([[1,3],[3,4],[5,7]])

array([[1, 3],
       [3, 4],
       [5, 7]])

In [13]:
# 
np.array([[1,3],[3,4],[9,8,7]])

C:\Users\Dell\AppData\Local\Temp\ipykernel_11832\2570925194.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4],[9,8,7]])


array([list([1, 3]), list([3, 4]), list([9, 8, 7])], dtype=object)

In [14]:
# in above case i m getting result but as array of list boz all the list are not having same no. of items inside them 

In [16]:
np.array([[[1,3],[3,4]],[[5,6],[9,7]]])   # this is called 3d array boz of 3 brackets 

array([[[1, 3],
        [3, 4]],

       [[5, 6],
        [9, 7]]])

In [17]:
# NOTE-- there is 1d , 2d , 3d and nd array

In [18]:
# we can creste array of any dimension like 
np.array([1,2,3],ndmin=3)    # ndmin=3 will create array of 3dimension like 

array([[[1, 2, 3]]])

In [19]:
# we can create array of any dimension like 30 here 
np.array([1,2,3],ndmin=30)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [20]:
# we can give datatype for items of array using--- dtype=     , like
np.array([1,2,3],ndmin=3,dtype=complex)
#  we will get all items as complex like

array([[[1.+0.j, 2.+0.j, 3.+0.j]]])

In [21]:
# 
np.array([(1,2),(4,5)])

array([[1, 2],
       [4, 5]])

In [22]:
# even integers are of different types like----16bit, 32bit,64bit and many more like
np.array([(1,2),(4,5)],dtype=[('a','<i4'),('b','<i8')])

array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [29]:
arr=np.array([(1,2),(4,5)],dtype=[('a','<i4'),('b','<i8')])

In [30]:
arr[0]

(1, 2)

In [31]:
arr[0][0]

1

In [32]:
arr[0][1]

2

In [33]:
type(arr[0][0])   #  so integer '1' is 32 bit  

numpy.int32

In [34]:
type(arr[0][1])    # integer '2' is 64 bit 

numpy.int64

In [35]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [36]:
#another high level datatype inside numpy is 'matrix' appart from 'array' 
np.mat(arr)

matrix([[(1, 2), (4, 5)]], dtype=[('a', '<i4'), ('b', '<i8')])

In [37]:
# another way of creating matrix is like
np.matrix(arr)     # both gives same result this one and the above one

matrix([[(1, 2), (4, 5)]], dtype=[('a', '<i4'), ('b', '<i8')])

In [38]:
# using 3 differnt ways for getting a array 1)np.array(l) 2)np.asarray(l)  3) np.asanyarray(l) but there is little diff. in 2 and 3 how 
l=[9,8,7,6,5,4]

In [39]:
#  np.array(l)
np.array(l)

array([9, 8, 7, 6, 5, 4])

In [40]:
# np.asarray(l)
np.asarray(l)

array([9, 8, 7, 6, 5, 4])

In [41]:
# np.asanyarray(l)
np.asanyarray(l)

array([9, 8, 7, 6, 5, 4])

In [42]:
# in all above 3 cases the results are same but if i use matrix in 2 and 3 to get array let's see what we will get

In [43]:
arr=np.mat([1,3])

In [44]:
arr

matrix([[1, 3]])

In [45]:
# let's put this inside np.array()
np.array(arr)

array([[1, 3]])

In [46]:
# let's put arr inside np.asanyarray()
np.asanyarray(arr)

matrix([[1, 3]])

In [47]:
#  u see the first gave array but the last one gave matrix this is the difference b/w  the two

In [49]:
# note--- there is a function called 'issubclass()' to check something is subclass of something or not 

#  like this ,here i want to check whether matrix is subclass of ndarray or  not 
issubclass(np.matrix,np.ndarray)

True

# NOTE---->>>>>>> matrix is a subclass of array or child class of array and array is the parent calss 

In [53]:
#  ndarray is not a subclass of matrix as it will give false 
issubclass(np.ndarray,np.matrix)

False

In [54]:
# deep-copy and shallow-copy 

In [57]:
arr1=np.array(arr)

In [58]:
arr1

array([[1, 3]])

In [65]:
# if i assign this array to any variable like 
a=arr1   # what happens if i do any changes in 'arr1' the same changes will be reflected in 'a' also and hence 'a' is called 'shallow-copy' of array arr1 

In [66]:
a

array([[56,  3]])

In [69]:
# but if i again assign the same array 'arr1' to new variable but this using --- b=np.copy(arr1)
b=np.copy(arr1)

In [70]:
b

array([[56,  3]])

In [72]:

arr1[0][0]=156   # here i m again replacing the previously replaced value which was '56' with new value '156'

In [73]:
arr1

array([[156,   3]])

In [74]:
# the same changes will be made in variabel 'a' also 
a

array([[156,   3]])

In [75]:
# but this change will not reflect in 'b'
b

array([[56,  3]])

In [ ]:
''' boz 'b' is called deep-copy of array 'arr1' and any changes in 'arr1' will not reflect in 'b' boz 'b' occupies differnt space in main memory 
 but 'a' is in same sapce of memory in which 'arr1' is there in main memory boz they are same''' 

In [77]:
# array elements are mutuable means we can change the arry elements 

In [78]:
arr1

array([[156,   3]])

In [79]:
arr1[0:10]

array([[156,   3]])

In [80]:
arr1[-1]

array([156,   3])

In [82]:
# using for loop getting the elements of array 
for i in arr1:
    print(i)

[156   3]


In [84]:
# fromfunction() ---helps to generate a array depending upon the logic we put inside the function like
np.fromfunction(lambda i,j:i==j,(4,4))  # fromfunction is another function in numpy ,lambda function we all know and (4,4) if for size of array 
#  array of size 4*4 having total of 16 elements 

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [85]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [87]:
# in numpy any no. divided by zero than we won't get error duvision by zero rather it will give 'inf' like
np.fromfunction(lambda i,j:i/j,(3,3))

C:\Users\Dell\AppData\Local\Temp\ipykernel_11832\1676616379.py:2: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j:i/j,(3,3))
C:\Users\Dell\AppData\Local\Temp\ipykernel_11832\1676616379.py:2: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j:i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [89]:
# generator
(i*i for i in range(5))

<generator object <genexpr> at 0x0000018746A174A0>

In [90]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [91]:
gen=(i*i for i in range(5))

In [92]:
gen

<generator object <genexpr> at 0x0000018746A17890>

In [94]:
#  there is another function in numpy--- fromiter()
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [97]:
# range()  itself is a generater function remember this 
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [104]:
# from string also i can generate the array using--- fromstring() , like
np.fromstring('1,2,3,4',sep=', ',dtype=int)

array([1, 2, 3, 4])

In [109]:
# from any other string also i can generate array like
np.fromstring('8,7,6,5',sep=',',dtype=complex)

array([8.+0.j, 7.+0.j, 6.+0.j, 5.+0.j])

In [111]:
# 
l=[6,5,4,3]
arr=np.array(l)

In [113]:
# 
arr1=np.array([[4,3,2,1],[7,6,5,4],[7,6,5,4]])

In [114]:
arr1

array([[4, 3, 2, 1],
       [7, 6, 5, 4],
       [7, 6, 5, 4]])

In [115]:
#  for checking the dimension of any array use-- arrayname.ndim
arr1.ndim

2

In [116]:
# u can see above that the dimension of arr1 is '2' which means i will be able to represent this data in 2-D plane using x-y plane olny 

In [117]:
#if we want to know the no. of elements inside any array we can use -- 'size' function  
arr1.size

12

In [119]:
# for knowing the no. of rows and no. of columns in any array  
arr1.shape

(3, 4)

In [120]:
# 3-no. of rows and 4-- no. of columns 

In [122]:
# every element of array 'arr1' is integer of 32 bit 
arr1.dtype

dtype('int32')

In [123]:
# let's generate a 3d array like
arr2=np.array([[[1,2,3],[5,4,3]],[[7,8,9],[45,46,37]]])

In [124]:
arr2

array([[[ 1,  2,  3],
        [ 5,  4,  3]],

       [[ 7,  8,  9],
        [45, 46, 37]]])

In [126]:
# let's check the dimension of arr2 array
arr2.ndim

3

In [127]:
#  so it's a 3-d array 

In [129]:
#  let's print the shape of this array 
arr2.shape

(2, 2, 3)

In [130]:
# (2,2,3)-- what it means ,it means 'arr2' array has 2 sets of data with shape (2,3) 2- rows and 3-columns as u can above also 

In [131]:
# generating a array of dim... 4 
arr3=np.array([[[[1,2,3],[5,4,3]],[[7,8,9],[45,46,37]],[[1,2,3],[5,4,3]],[[1,2,3],[5,4,3]]]])

In [132]:
arr3

array([[[[ 1,  2,  3],
         [ 5,  4,  3]],

        [[ 7,  8,  9],
         [45, 46, 37]],

        [[ 1,  2,  3],
         [ 5,  4,  3]],

        [[ 1,  2,  3],
         [ 5,  4,  3]]]])

In [133]:
arr3.ndim

4

In [135]:
arr3.shape   # we have 4 sets of data of shape(2,3) with 2 rows and 3 columns 

(1, 4, 2, 3)

In [141]:
# range() is a generator function which only takes integers not float like
list(range(6))


[0, 1, 2, 3, 4, 5]

In [142]:
list(range(8.8))

TypeError: 'float' object cannot be interpreted as an integer

In [143]:
#  but in numpy there is one function-- arange(),  which is equivalent to range() function but in terms of operation and it can also take floating no. also 

In [145]:
np.arange(8.8)     # we will get array 

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [146]:
#  we can also generate array with jump also using 'arange()' which is kind of substitute of range() function available in core python  
np.arange(2.3,9,0.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3, 5.6, 5.9,
       6.2, 6.5, 6.8, 7.1, 7.4, 7.7, 8. , 8.3, 8.6, 8.9])

In [147]:
#  in reverse order to we can generate array like
np.arange(9,2.3,-0.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6, 6.3, 6. , 5.7, 5.4,
       5.1, 4.8, 4.5, 4.2, 3.9, 3.6, 3.3, 3. , 2.7, 2.4])

In [148]:
# like range() function arange() also excludes upper bound 

In [149]:
# linspace()-- is another function in numpy for generating random data in b\w two given points 
np.linspace(3,8)     # by-default it generates '50' random data values in b\w points given 

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [150]:
len(np.linspace(3,8))

50

In [152]:
#  but if we specify the no. of data points we want in b\w given points we can do this as
np.linspace(3,8,5)   # 5-- is the no. of data points which i want 

array([3.  , 4.25, 5.5 , 6.75, 8.  ])

In [153]:
# zeros()-- function in numpy for generating data with values '0'
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [156]:
np.zeros([2,3])   # data(array) with values  '0' in 2-rows and 3-columns 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [158]:
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [159]:
# ones()--function similar to zeros() function but for grnerating array with values as'1'
np.ones(5)

array([1., 1., 1., 1., 1.])

In [161]:
np.ones([2,3])             # 2-d 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [162]:
# 3-d
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [164]:
# empty()-- function
np.empty(5)

array([1., 1., 1., 1., 1.])

In [166]:
np.empty([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [168]:
# identity matrix with function ---->  eye()
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [173]:
# 
np.linspace(2,4,4,endpoint=False)  # with endpoint=False  it will not enclude the last no. which is 4 here 

array([2. , 2.5, 3. , 3.5])

In [174]:
np.linspace(2,4,4) # in this case it will enclude the end point 

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [177]:
# logspace()-- function which will give values of randomly generated points b/w given start and stop point values on 'log' scale
np.logspace(2,5,5) 

array([   100.        ,    562.34132519,   3162.27766017,  17782.79410039,
       100000.        ])

In [178]:
#### numpy functions which will be mostly used on daily bases 

In [182]:
# generating 40 random data points b/w 2 and 5  
d=np.linspace(2,5,40)

In [183]:
d

array([2.        , 2.07692308, 2.15384615, 2.23076923, 2.30769231,
       2.38461538, 2.46153846, 2.53846154, 2.61538462, 2.69230769,
       2.76923077, 2.84615385, 2.92307692, 3.        , 3.07692308,
       3.15384615, 3.23076923, 3.30769231, 3.38461538, 3.46153846,
       3.53846154, 3.61538462, 3.69230769, 3.76923077, 3.84615385,
       3.92307692, 4.        , 4.07692308, 4.15384615, 4.23076923,
       4.30769231, 4.38461538, 4.46153846, 4.53846154, 4.61538462,
       4.69230769, 4.76923077, 4.84615385, 4.92307692, 5.        ])

In [184]:
d.ndim   # so it is a 1-d data 

1

In [187]:
d.shape   # 40- columns and only 1 - row

(40,)

In [189]:
#  we can change the shape of the above data using-- reshape() function like
d.reshape(40,1)   # data with 40- rows and only 1 -column

array([[2.        ],
       [2.07692308],
       [2.15384615],
       [2.23076923],
       [2.30769231],
       [2.38461538],
       [2.46153846],
       [2.53846154],
       [2.61538462],
       [2.69230769],
       [2.76923077],
       [2.84615385],
       [2.92307692],
       [3.        ],
       [3.07692308],
       [3.15384615],
       [3.23076923],
       [3.30769231],
       [3.38461538],
       [3.46153846],
       [3.53846154],
       [3.61538462],
       [3.69230769],
       [3.76923077],
       [3.84615385],
       [3.92307692],
       [4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ]])

In [190]:
# using reshape() function we can get all possible sets of data but always remember that the size of both should be same  

In [193]:
d.reshape(2,2,10)   # 2 sets of 2*10 

array([[[2.        , 2.07692308, 2.15384615, 2.23076923, 2.30769231,
         2.38461538, 2.46153846, 2.53846154, 2.61538462, 2.69230769],
        [2.76923077, 2.84615385, 2.92307692, 3.        , 3.07692308,
         3.15384615, 3.23076923, 3.30769231, 3.38461538, 3.46153846]],

       [[3.53846154, 3.61538462, 3.69230769, 3.76923077, 3.84615385,
         3.92307692, 4.        , 4.07692308, 4.15384615, 4.23076923],
        [4.30769231, 4.38461538, 4.46153846, 4.53846154, 4.61538462,
         4.69230769, 4.76923077, 4.84615385, 4.92307692, 5.        ]]])

In [195]:
d.reshape(2,2,20)  # boz the size of two are different

ValueError: cannot reshape array of size 40 into shape (2,2,20)

In [1]:
# for generating a random data we have 2 functions in numpy 1)np.random.rand()   2) np.random.randn()
# there is difference b/w two 1) the 'rand' will generate only positive data using 'unifor ditribution'
#  2) where as 'randn' generates data which contains -ve values also using 'standard normal distribution'

In [2]:
#  there is diff. b/w noraml distribution and stand. noraml distribution 
#  IN NORAML DISTRIBUTION-- the mean value and the standard deviation value can be any thing
# IN STANDARD NORMAL DISTRIBITION ---- the mean=0 and stand.. diviation=1 

In [3]:
# using 'rand' for generating random data values 
import numpy as np
np.random.rand(3)

array([0.32264777, 0.96655846, 0.06033754])

In [6]:
#  using 'randn' for generating random data values like
a=np.random.randn(5)

In [7]:
#  youn can see -ve values also 
a

array([-1.23976719, -0.98637286, -1.0045526 ,  0.09123411, -1.29803586])

In [8]:
#  let's check the dimension 
a.ndim

1

In [10]:
#  we can random data of any dimension like
np.random.randn(2,3)   # 2- is for no. of rows and 3-- is for no. of columns
#  dimension is 2

array([[-0.42101313, -0.74486868,  0.3108301 ],
       [ 0.18278298, -0.43327808,  0.24600529]])

In [11]:
# 3 dimensional random data generated  like
np.random.rand(2,2,4)

array([[[0.47019715, 0.58953279, 0.49549646, 0.99281337],
        [0.3968812 , 0.16102944, 0.56289354, 0.7328253 ]],

       [[0.79513822, 0.95416806, 0.4904465 , 0.05815877],
        [0.27899488, 0.45104006, 0.41187854, 0.77109748]]])

In [12]:
#  2 sets of 2*3 data with 2-- rows and 3- columns in each set 

In [13]:
#  there is another function for randomly generating integer value b/w given lower value and upper value like  

In [14]:
np.random.randint(2,5)

3

In [16]:
np.random.randint(2,10,size=10)    # random points b/w 2(included) & 10(excluded) with size=10 means will generate total of 10 points

array([7, 5, 2, 8, 6, 6, 6, 9, 2, 5])

In [20]:
b=np.random.randint(2,10,size=(2,3))
b

array([[9, 3, 7],
       [3, 7, 4]])

In [18]:
#  so basically give the size you want and the lower value and upper value for data points values in b/w those lower and upper values   

In [21]:
#  reshaping of above data which we have generated 
b.reshape(3,2)

array([[9, 3],
       [7, 3],
       [7, 4]])

In [22]:
b.reshape(1,6)

array([[9, 3, 7, 3, 7, 4]])

In [23]:
b.reshape(6,1)

array([[9],
       [3],
       [7],
       [3],
       [7],
       [4]])

In [27]:
b.reshape(1,1,6)  # 3-d data 

array([[[9, 3, 7, 3, 7, 4]]])

In [29]:
# 
b.reshape(3,-1)   # 'b' originally is havingn total of 6 elements and here 3-- no. of rows so here in this case it will automatically take 2-columns 

array([[9, 3],
       [7, 3],
       [7, 4]])

In [30]:
#  using max()  and min() function we can get max.. and min.. values out of any array of any dimension like 

In [31]:
b.max()

9

In [32]:
b.min()

3

In [33]:
#  let's generate a array of size 5,5
arr=np.random.randint(4,100,size=(5,5))

In [34]:
arr

array([[50, 43,  4, 60, 41],
       [31, 37, 85,  9, 51],
       [70, 82, 74, 67, 91],
       [91, 71, 93, 87, 96],
       [83, 75, 56, 67, 25]])

In [35]:
# we want elements from intersection of 3,4 rows and 3,4 columns   
arr[3:,3:]   # 3: means start from 3rd row and go till end and second 3: means start from 3rd column and go till end

array([[87, 96],
       [67, 25]])

In [38]:
arr[1,3]   # for getting enement at any location in array ,using which row and in which column 

9

In [39]:
## suppose if i want data of 2nd and 4th columns than 
# index for 2nd column is '1' and for 4th column is '3' we use indexes like 
#  we want data for all rows and only for columns with index '1' and '3'
arr[:,[1,3]]


array([[43, 60],
       [37,  9],
       [82, 67],
       [71, 87],
       [75, 67]])

In [40]:
#in similar way we can get data of any specific rows like say i want data for row with index '1' and '3' than 
arr[[1,3],:]

array([[31, 37, 85,  9, 51],
       [91, 71, 93, 87, 96]])

In [41]:
# now give me all values of array 'arr' which are >10 like
arr[arr>10]

array([50, 43, 60, 41, 31, 37, 85, 51, 70, 82, 74, 67, 91, 91, 71, 93, 87,
       96, 83, 75, 56, 67, 25])

In [43]:
arr>10   # value which is >10 will return True and all other as False 

array([[ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [45]:
# elements wise multiplication of same size arrays like 
arr*arr     # we can have diff.. arrays also 

array([[2500, 1849,   16, 3600, 1681],
       [ 961, 1369, 7225,   81, 2601],
       [4900, 6724, 5476, 4489, 8281],
       [8281, 5041, 8649, 7569, 9216],
       [6889, 5625, 3136, 4489,  625]])

In [46]:
# multiplying any no. with array than the no. will be multiplied with every element  of array 'arr' like
arr*2

array([[100,  86,   8, 120,  82],
       [ 62,  74, 170,  18, 102],
       [140, 164, 148, 134, 182],
       [182, 142, 186, 174, 192],
       [166, 150, 112, 134,  50]])

In [47]:
# we can also divede by any no. also like 
arr/2

array([[25. , 21.5,  2. , 30. , 20.5],
       [15.5, 18.5, 42.5,  4.5, 25.5],
       [35. , 41. , 37. , 33.5, 45.5],
       [45.5, 35.5, 46.5, 43.5, 48. ],
       [41.5, 37.5, 28. , 33.5, 12.5]])

In [49]:
arr/arr  # for converting any array into array with all values '1' unity like  

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
# let's see what is 'BROADCASTING' in array
#  there is something called 'row wise broadcasting' and 'colunm wise broadcasting' like

In [53]:
# row wise broascasting 
arr=np.zeros(5)

In [54]:
arr

array([0., 0., 0., 0., 0.])

In [55]:
arr+5

array([5., 5., 5., 5., 5.])

In [57]:
arr1=np.zeros([5,5])

In [58]:
arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
b=np.array([1,1,2,3,4])

In [60]:
b

array([1, 1, 2, 3, 4])

In [61]:
#  row wise broadcasting 
arr1+b

array([[1., 1., 2., 3., 4.],
       [1., 1., 2., 3., 4.],
       [1., 1., 2., 3., 4.],
       [1., 1., 2., 3., 4.],
       [1., 1., 2., 3., 4.]])

In [64]:
b.T   # not able to get transpose boz it is simply 1 dimensional ,first change it to 2-D or any higher dim... like

array([1, 1, 2, 3, 4])

In [65]:
b=np.array([[1,2,3,4,5]])

In [66]:
b

array([[1, 2, 3, 4, 5]])

In [67]:
b.ndim

2

In [68]:
# transpose of array 'b'
b.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [69]:
b.shape

(1, 5)

In [71]:
#  now column wise broadcasting like
arr1+b.T

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [72]:
# can also do 
arr1+5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [73]:
# various opeartions with any array like 
arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
arr1=np.random.randn(3,5)

In [75]:
arr1

array([[-0.76166835,  1.67366862, -0.17486123, -0.23443948,  1.12657093],
       [-0.88342136, -1.57978706,  1.2918349 , -0.64818562,  0.10264449],
       [-0.02094611, -0.26431721,  0.3542523 ,  0.54363755, -0.81503681]])

In [76]:
#  we can get squareroot of each value of above array like 
np.sqrt(arr1)   # sqrt()-- function is available in numpy also along with 'math' library of python 

C:\Users\Dell\AppData\Local\Temp\ipykernel_10512\3592223419.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr1)   # sqrt()-- function is available in numpy also along with 'math' library of python


array([[       nan, 1.29370345,        nan,        nan, 1.06140046],
       [       nan,        nan, 1.13658915,        nan, 0.32038178],
       [       nan,        nan, 0.59519098, 0.73731781,        nan]])

In [77]:
#  it is returning 'nan' where there is -ve value 

In [78]:
# taking exponent of each value of 'arr1' like 
np.exp(arr1)

array([[0.46688684, 5.33169193, 0.83957352, 0.7910141 , 3.08505947],
       [0.41336621, 0.20601896, 3.63945847, 0.52299382, 1.1080974 ],
       [0.97927174, 0.76772997, 1.4251147 , 1.72226029, 0.44262303]])

In [81]:
#  we can take 'log' of every value of 'arr1' also like
np.log(arr1)     # with base value=e  # we can change base to any value which we want

C:\Users\Dell\AppData\Local\Temp\ipykernel_10512\2657877095.py:2: RuntimeWarning: invalid value encountered in log
  np.log(arr1)     # with base value=e  # we can change base to any value which we want


array([[        nan,  0.515018  ,         nan,         nan,  0.11917845],
       [        nan,         nan,  0.25606361,         nan, -2.27648384],
       [        nan,         nan, -1.03774591, -0.60947253,         nan]])

In [82]:
# again where there is -ve value it is returning 'nan'

In [85]:
# there is another function in numpy -- seed()   for freezing the randomly generated values using any of like (rand,randn & randint)
np.random.seed(12)
np.random.rand(2,3)

array([[0.15416284, 0.7400497 , 0.26331502],
       [0.53373939, 0.01457496, 0.91874701]])

In [ ]:
#  as you can see every time you run the command now values are not changing boz of use of 'seed()' function of numpy  